test again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -131,6 +131,10 @@ jobs:
       - uses: actions/checkout@v2
       - name: Install Dependencies
         run: yarn install
+      - name: Build GraphQL PPX
+        run: |
+          cd node_modules/@reasonml-community/graphql-ppx
+          yarn build || echo "Build failed, continuing"
       - name: Compile ReScript files
         run: yarn run re:build
   dockerhub-master:
